### ISSUE TITLE
Residual lines do not appear

### ISSUE THREAD

**Issue by phet-steele** [phetsims/curve-fitting#14] opened 2015-05-18 17:57 UTC
The error bars turn gray and lose their vertical lines when "Residuals" is checked.

![gray error](https://cloud.githubusercontent.com/assets/5863899/7686689/e8531404-fd54-11e4-855e-3c47ae53cb1d.PNG)

Tested on Win 8.1 browsers.

Troubleshooting information (do not edit):
Name: Curve Fitting
URL: http://www.colorado.edu/physics/phet/dev/html/curve-fitting/1.0.0-dev.4/curve-fitting_en.html?dev
Version: 1.0.0-dev.4 2015-05-18 16:31:51 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 6.3; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0
Language: en-US
Window: 1366x633
Pixel Ratio: 1/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (Mozilla)
Vertex: attribs: 16 varying: 28 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {"comment":"# curve-fitting 1.0.0-dev.4 Mon May 18 2015 10:31:50 GMT-0600 (Mountain Daylight Time)","curve-fitting":{"sha":"e701e0eb5ee5f5dfbbe194fcc31bbd52e354a238","branch":"master"},"assert":{"sha":"903564a25a0f26acdbd334d3e104039864b405ef","branch":"master"},"axon":{"sha":"1199217e4b4a158afe5cf2fd59e5a7a087fd4179","branch":"master"},"babel":{"sha":"3ef6bce9237080ffa2d92c30d28b2d6f966bddc4","branch":"master"},"brand":{"sha":"b3362651f1d7eddb7f8697d02400472f97f9d140","branch":"master"},"chipper":{"sha":"8fd8eb6a428c4ea10ce8511af0f2cce6bfc61612","branch":"master"},"dot":{"sha":"9e70b8cac3ddfcb9e1dff786b23bc64de3b98350","branch":"master"},"joist":{"sha":"c9f2b67459f59f292a59bca7a714cd6f0908b4f9","branch":"master"},"kite":{"sha":"affd230ecc0d01f4f217ed7060007e3c71de4937","branch":"master"},"phet-core":{"sha":"23834d107dc1cb368c00901c76927b712b9caa10","branch":"master"},"phetcommon":{"sha":"bb92c52cd90fdaa0c2a746fea82594afd439b4db","branch":"master"},"scenery":{"sha":"a69dfeb8452edb51348eb2187ce25939a8b0dda1","branch":"master"},"scenery-phet":{"sha":"4ca937ebfe35a021d4c781a4c6877be22ddbcf9b","branch":"master"},"sherpa":{"sha":"7c1f8f58b67a29014fb75ef4c80c3a5904193630","branch":"master"},"sun":{"sha":"5ae6c12634dc188f5b9ba8bc3aca76dcf96448c8","branch":"master"},"vegas":{"sha":"5d1f054ececac34752bbd2edcf940a6fdfdcb017","branch":"master"},"vibe":{"sha":"bad425472494babb88c260adbd718230d567ec3a","branch":"master"}}

**Comment by amanda-phet** [comment] 2015-05-20 03:19
The error bars should turn gray. However, you found a bug that made the residual lines not appear. Can you reproduce it? 

This is what it is supposed to look like:

![screen shot 2015-05-19 at 9 18 26 pm](https://cloud.githubusercontent.com/assets/7852916/7718375/ae47f48c-fe6c-11e4-8aa8-2fa67572541e.png)

**Comment by amanda-phet** [comment] 2015-05-20 03:41
I just thought I'd try to reproduce it and realized you only had two points and a linear fit... since two points make a line the points will be exactly on the line, hence no residuals. 

I'll go ahead and close this since there doesn't appear to be a problem.

**Closed by amanda-phet** 2015-05-20 03:41 UTC

**Comment by phet-steele** [comment] 2015-05-20 03:54
The lines I was talking about were the lines that go from the point to the little horizontal lines on top and bottom of the point. It's making more sense to me now as to why it is practical those aren't shown.
