### ISSUE TITLE
Chi-squared looks messy with long strings

### ISSUE THREAD

**Issue by phet-steele** [phetsims/curve-fitting#28] opened 2015-05-22 17:22 UTC
Chi-squared looks messy with long strings

![high chi](https://cloud.githubusercontent.com/assets/5863899/7775972/ba4aedac-0074-11e5-9acb-ce86ef552c24.PNG)

Tested on Win 8.1 browsers
Troubleshooting information:
Name: Curve Fitting
URL: http://www.colorado.edu/physics/phet/dev/html/curve-fitting/1.0.0-dev.4/curve-fitting_en.html
Version: 1.0.0-dev.4 2015-05-18 16:31:51 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 6.3; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0
Language: en-US
Window: 1366x633
Pixel Ratio: 1/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (Mozilla)
Vertex: attribs: 16 varying: 28 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {"comment":"# curve-fitting 1.0.0-dev.4 Mon May 18 2015 10:31:50 GMT-0600 (Mountain Daylight Time)","curve-fitting":{"sha":"e701e0eb5ee5f5dfbbe194fcc31bbd52e354a238","branch":"master"},"assert":{"sha":"903564a25a0f26acdbd334d3e104039864b405ef","branch":"master"},"axon":{"sha":"1199217e4b4a158afe5cf2fd59e5a7a087fd4179","branch":"master"},"babel":{"sha":"3ef6bce9237080ffa2d92c30d28b2d6f966bddc4","branch":"master"},"brand":{"sha":"b3362651f1d7eddb7f8697d02400472f97f9d140","branch":"master"},"chipper":{"sha":"8fd8eb6a428c4ea10ce8511af0f2cce6bfc61612","branch":"master"},"dot":{"sha":"9e70b8cac3ddfcb9e1dff786b23bc64de3b98350","branch":"master"},"joist":{"sha":"c9f2b67459f59f292a59bca7a714cd6f0908b4f9","branch":"master"},"kite":{"sha":"affd230ecc0d01f4f217ed7060007e3c71de4937","branch":"master"},"phet-core":{"sha":"23834d107dc1cb368c00901c76927b712b9caa10","branch":"master"},"phetcommon":{"sha":"bb92c52cd90fdaa0c2a746fea82594afd439b4db","branch":"master"},"scenery":{"sha":"a69dfeb8452edb51348eb2187ce25939a8b0dda1","branch":"master"},"scenery-phet":{"sha":"4ca937ebfe35a021d4c781a4c6877be22ddbcf9b","branch":"master"},"sherpa":{"sha":"7c1f8f58b67a29014fb75ef4c80c3a5904193630","branch":"master"},"sun":{"sha":"5ae6c12634dc188f5b9ba8bc3aca76dcf96448c8","branch":"master"},"vegas":{"sha":"5d1f054ececac34752bbd2edcf940a6fdfdcb017","branch":"master"},"vibe":{"sha":"bad425472494babb88c260adbd718230d567ec3a","branch":"master"}}

**Comment by amanda-phet** [comment] 2015-06-01 18:56
@phet-steele Can you let me know how to reproduce this? I can't get X^2 to be that big. Thanks!

**Comment by phet-steele** [comment] 2015-06-01 19:29
1. You're going to need at least five points.
2. I select the cubic curve, it seems to work pretty well for this.
3. Bring the error for each of the points to its minimum, then put them all relatively on the same x value. Try to make your y intercept as big as possible:

![chi squared rises](https://cloud.githubusercontent.com/assets/5863899/7921325/e895f004-0861-11e5-9712-ad91261b7192.PNG)

4. Switch to the adjustable fit line (you'll have to switch to adjustable fit, back to best fit, then again back to adjustable fit due to issue #23).
5. There you go! You can move the sliders around to make it even bigger.

**Comment by amanda-phet** [comment] 2015-06-01 20:00
After talking with @phet-steele it seems like the issue is very much related to #13. If the adjustable fit sliders "remember" where they were when switching between best fit and adjustable fit, we won't get a X^2 that large. When on Best fit, the largest I've gotten X^2 is in the thousands, and the value just barely fits in the window. I will open a separate issue to address fitting large numbers, but will wait and see if @phet-steele can make X^2 even larger using only Best fit.

![screen shot 2015-06-01 at 1 56 58 pm](https://cloud.githubusercontent.com/assets/7852916/7921989/8da0cc00-0866-11e5-85c7-5bc2e609f282.png)

**Comment by phet-steele** [comment] 2015-06-01 23:48
Best I could do with best fit at the moment. 1 point at each corner with quadratic puts me in the ten thousands:

![chi squared sleeps in](https://cloud.githubusercontent.com/assets/5863899/7925777/4245e2fc-0886-11e5-8fa4-1c367229a90d.PNG)

**Comment by phet-steele** [comment] 2015-06-02 00:03
Well turns out there are situations where I can continuously add points to certain locations and the value will be increasing for every new point. It's a very slow process, but in theory and with enough time the value could get very long.

**Comment by memo330179** [comment] 2016-07-01 14:01
I have removed the decimals from the large numbers as suggested by @veillette I've also added a max-width to scale the text down for truly large numbers.

![curve fitting screenshot](https://cloud.githubusercontent.com/assets/11654721/16523707/c37b8a10-3f72-11e6-961b-aac578fedd9d.png)

**Comment by memo330179** [comment] 2016-07-01 14:02
Assigning to @veillette for review

**Comment by pixelzoom** [comment] 2016-08-05 18:38
I'll review this later, as part of a more thorough test of i18n.

**Comment by SaurabhTotey** [comment] 2019-06-03 17:24
It looks like the X^2 value displays well for most reasonable X^2 values, but I am able to get ridiculously large X^2 values where the current solution may not be optimal. It may be possible that the numbers will need to be represented with a multiplication with a power of ten.

Here is what the sim looks like with ridiculous X^2 values.
<img width="1386" alt="Screen Shot 2019-06-03 at 11 15 25 AM" src="https://user-images.githubusercontent.com/22577113/58821146-ac8c5000-85f1-11e9-95a3-9b278a41e77a.png">

I was able to achieve this by setting the `snapToGrid` query parameter to true, placing 2 points at the same location on the rightmost position on the x-axis, using an adjustable cubic curve, and setting all the curve parameters to their lowest setting.

**Comment by pixelzoom** [comment] 2019-06-03 17:32
That is indeed a big value.  `ScientificNotationNode`  probably wouldn't be of much help, because it would display something like 1.43 x 10<sup>10</sup>, which has a similar "width" problem.  I'm not sure what to suggest here.

**Comment by SaurabhTotey** [comment] 2019-06-06 17:24
Assigning to @ariel-phet to see what should be done about extremely large X^2 values.

**Comment by ariel-phet** [comment] 2019-06-06 21:46
@SaurabhTotey I think the learning goal here is that big Chi^2 values means not good fit.

My suggestion is that above a value of 1000 you change the equal sign to a `>` symbol and just pin the value at 1000, so above 1000 it would read 

> X^2 > 1000

The actual value is not so important at that point, just that it has gotten big

**Comment by SaurabhTotey** [comment] 2019-06-07 17:40
As of right now in master, below is what the Chi Squared readout looks like.
<img width="186" alt="chisquaredindeviationsaccordionbox" src="https://user-images.githubusercontent.com/22577113/59122746-c2af4e80-8918-11e9-9ed2-0e1643e5e636.png">
The '>' sign is used whenever the Chi Squared gets above 1000, and the value is capped at 1000. Otherwise, the readout functions as normal. As I believe this issue is now resolved, I am marking this issue as ready for review.

**Closed** 2019-06-11 22:13 UTC
Labels: design:general, status:ready-for-review
