### ISSUE TITLE
edge case for rSquare 

### ISSUE THREAD

**Issue by veillette** [phetsims/curve-fitting#86] opened 2016-07-27 15:32 UTC
In cases where the points share all the same y value, an issue arises with the calculation of r Square. In this case the best fit line is a horizontal line. However the value of r square is undefined.
r^2=1 - (numerator/denominator) where the denominator vanishes. 

FYI, the denominator is essentially the y variance of the points and is equal to zero if all the points fall onto a horizontal line. 
The numerator for the best fit line is equal to zero as well. In the case of adjustable fit, the numerator can range from 0 to a positive number. 

How should we handle this case? Here are three possible options:
- Obviously the best fit line is very good, there are no residuals, so we could treat this case by hand, setting it to 1. However, when it comes to rSquare value for the adjustable fit, then we are in uncharted territory. I don't know to handle that case. 
- On the other hand we could set r square to zero.  In this case, for best fit line and adjustable fit it is always zero. The readout reads zero.  
- Set r square to null for best fit line and adjustable fit (barometer length is zero), The readout of r square value is left blank.

For reference, here is how is was handled in linear regression.
https://github.com/phetsims/least-squares-regression/issues/63

**Comment by ariel-phet** [comment] 2016-07-27 16:29
@veillette I think if we can handle it the same way we did in linear regression would be the most consistent.

**Comment by veillette** [comment] 2016-08-02 18:27
Thanks @ariel-phet .
 
For the record, the flash version of curve fitting uses the second approach. r^2 is zero for best fit and adjustable fit and the read out indicates zero.

In any case, we will need to check when the variance,  
 (yyAverage - yAverage * yAverage))  is equal to zero.

**Comment by SaurabhTotey** [comment] 2019-06-03 17:11
As of right now, it seems like r^2 is 1 for a perfectly horizontal line for both best fit and adjustable fit. However, for adjustable fit, it seems like the r^2 is always 1 regardless of how well the adjustable fit actually models the points. In adjustable fit, I can get situations where the r^2 is 1 and the X^2 value is 4325. I will spend some time trying to get the behavior where r^2 will be 0 for both best and adjustable fits.

**Comment by SaurabhTotey** [comment] 2019-06-03 17:52
This issue is now seemingly fixed in 008a420. It now sets the r^2 to 0 whenever all the points are perfectly horizontal. r^2 is set to 0 for both adjustable fit and best fit.

**Comment by SaurabhTotey** [comment] 2019-06-07 18:18
I previously hadn't realized that the flash simulation and the least squares regression sim handled this case differently. As such, I made the behaviour of this sim match that of least squares regression. Now, for perfectly horizontal points, there is no readout for r^2. r^2 only has a value (that can still be 0) whenever the points are not exactly horizontal. This solution most closely resembles the 3rd solution posed by @veillette originally, where the only difference is that I use NaN internally rather than null because that is what is described in https://github.com/phetsims/least-squares-regression/issues/63.

**Closed** 2019-06-12 18:12 UTC
Labels: status:ready-for-review, type:question
