### ISSUE TITLE
Continuously manipulating sliders causes contradictory graphs

### ISSUE THREAD

**Issue by phet-steele** [phetsims/curve-fitting#37] opened 2015-08-10 18:21 UTC
On a touch screen:
1. Put some points on the graph and check "Curve".
2. Select the Cubic curve type (also works with Quadratic but is not as dramatic).
3. Select Adjustable fit.
4. Place Finger A on the "a" slider.
5. Without letting up on Finger A, use a different Finger B to switch the curve type to linear or quadratic.
6. Wiggle Finger A and you'll notice you still control the "a" slider even though it isn't shown, and the graph that is displayed still appears cubic in shape:

![img_0027](https://cloud.githubusercontent.com/assets/5863899/9179497/376e4d14-3f5a-11e5-9a7a-cf4009e7062b.PNG)

Tested on iPad Air 2 in 35be4367fa4ffeb1ac43f39fc84864642c2e2b8e while verifying #13 and #15.

**Comment by memo330179** [comment] 2016-06-30 15:08
assigning to @veillette for review

**Comment by veillette** [comment] 2017-04-17 17:38
I have been to aggressive in  removing cruft and I reintroduced  this bug.

**Comment by SaurabhTotey** [comment] 2019-06-07 21:43
I am unable to reproduce this behavior on master. I believe this issue has been fixed for a while. In `view/FitPanel.js`, I see a comment on line 148 that mentions this issue and disables irrelevant sliders. I believe that that code should be enough to prevent this issue. Consequently, I am marking this issue as ready for review, because I believe that this issue no longer exists.

**Closed** 2019-06-11 22:07 UTC
Labels: status:ready-for-review, type:bug, type:multitouch
